import type {
  AdminChannel,
  AdminModel,
  AdminUser,
  Asset,
  ModelConfig,
  Order,
  Project,
  StoryboardShot,
  Task,
  User,
  Work,
} from './types'

/* 每个键都指向不同的画面，避免不同候选 / 作品复用同一张示例图 */
export const media = {
  auroraCover: '/media/hero-mountains.png',
  cityCover: '/media/city-architecture.png',
  portrait: '/media/portrait-reference.png',
  dancer: '/media/action-reference.png',
  forest: '/media/shot-forest-path.png',
  architecture: '/media/city-architecture.png',
  product: '/media/studio-still-life.png',
  stillLife: '/media/shot-letter-desk.png',
  studio: '/media/shot-interior-push.png',
  auroraSky: '/media/shot-aurora-sky.png',
  cityNight: '/media/work-city-night.png',
  video: 'https://assets.mixkit.co/videos/29467/29467-720.mp4',
  videoPoster: '/media/video-aurora-poster.png',
  cityVideoPoster: '/media/city-architecture.png',
}

export const demoUser: User = {
  id: 'user-mira',
  name: 'Mira Chen',
  email: 'mira@oaooao.studio',
  role: 'admin',
  avatar: media.portrait,
  plan: 'Creator Pro',
  credits: 1240,
}

export const projects: Project[] = [
  {
    id: 'aurora',
    title: '极光之后',
    type: '短剧',
    cover: media.auroraCover,
    updatedAt: '刚刚',
    status: '进行中',
    progress: 68,
    tags: ['夜景', '人物关系', '16:9'],
    shotCount: 24,
    chapterCount: 4,
    description: '一段发生在极夜小镇的关于重逢与选择的短篇故事。',
    favorite: true,
  },
  {
    id: 'northline',
    title: 'Northline 城市样片',
    type: '品牌视觉',
    cover: media.cityCover,
    updatedAt: '昨天',
    status: '进行中',
    progress: 42,
    tags: ['城市', '建筑', '品牌片'],
    shotCount: 12,
    chapterCount: 2,
    description: '为 Northline 生活方式品牌制作的城市视觉样片。',
    favorite: false,
  },
  {
    id: 'quiet-room',
    title: '安静的房间',
    type: '个人作品',
    cover: media.studio,
    updatedAt: '3 天前',
    status: '已完成',
    progress: 100,
    tags: ['室内', '静物', '4:5'],
    shotCount: 8,
    chapterCount: 1,
    description: '一组关于光线、生活痕迹与留白的图片作品。',
    favorite: true,
  },
  {
    id: 'red-shift',
    title: 'Red Shift 产品故事',
    type: '广告片',
    cover: media.product,
    updatedAt: '6 天前',
    status: '已归档',
    progress: 100,
    tags: ['产品', '运动', '短视频'],
    shotCount: 10,
    chapterCount: 1,
    description: '一支以运动鞋为主角的节奏型产品短片。',
    favorite: false,
  },
]

export const assets: Asset[] = [
  {
    id: 'asset-aurora-01',
    kind: 'image',
    title: '极夜山谷参考',
    src: media.auroraCover,
    fallback: '山谷夜景',
    dimensions: '2400 × 1600',
    tags: ['极光之后', '夜景', '参考'],
    size: '4.8 MB',
    status: '可用',
    projectIds: ['aurora'],
    referencedBy: ['镜头 02', '镜头 07'],
    createdAt: '今天 09:41',
  },
  {
    id: 'asset-portrait-01',
    kind: 'image',
    title: '女主角肖像',
    src: media.portrait,
    fallback: '人物肖像',
    dimensions: '1600 × 2000',
    tags: ['角色', '林夏', '参考'],
    size: '2.1 MB',
    status: '可用',
    projectIds: ['aurora'],
    referencedBy: ['角色 · 林夏'],
    createdAt: '昨天 17:12',
  },
  {
    id: 'asset-dancer-01',
    kind: 'image',
    title: '动作姿态参考',
    src: media.dancer,
    fallback: '舞者动作',
    dimensions: '1800 × 2400',
    tags: ['动作', '姿态', '参考'],
    size: '3.6 MB',
    status: '可用',
    projectIds: ['aurora', 'northline'],
    referencedBy: ['镜头 11'],
    createdAt: '昨天 14:05',
  },
  {
    id: 'asset-city-01',
    kind: 'image',
    title: '城市玻璃幕墙',
    src: media.architecture,
    fallback: '玻璃建筑',
    dimensions: '2400 × 1600',
    tags: ['Northline', '建筑', '城市'],
    size: '5.2 MB',
    status: '可用',
    projectIds: ['northline'],
    referencedBy: ['画布节点 04'],
    createdAt: '周一 11:30',
  },
  {
    id: 'asset-forest-01',
    kind: 'scene',
    title: '北方森林场景',
    src: media.forest,
    fallback: '森林场景',
    dimensions: '2400 × 1600',
    tags: ['场景', '森林', '冷色'],
    size: '3.9 MB',
    status: '可用',
    projectIds: ['aurora'],
    referencedBy: ['场景 · 林间小路'],
    createdAt: '上周五 18:23',
  },
  {
    id: 'asset-voice-01',
    kind: 'audio',
    title: '极光之后 · 临时配乐',
    src: '',
    fallback: '音频',
    duration: '02:18',
    tags: ['音乐', '氛围', '临时'],
    size: '8.4 MB',
    status: '可用',
    projectIds: ['aurora'],
    referencedBy: ['成片音轨'],
    createdAt: '上周四 10:10',
  },
  {
    id: 'asset-city-video',
    kind: 'video',
    title: '城市穿行素材',
    src: media.video,
    poster: media.cityVideoPoster,
    fallback: '城市视频',
    duration: '00:12',
    dimensions: '1920 × 1080',
    tags: ['视频', '城市', '运动镜头'],
    size: '28.7 MB',
    status: '处理中',
    projectIds: ['northline'],
    referencedBy: [],
    createdAt: '周三 16:49',
  },
]

export const models: ModelConfig[] = [
  {
    id: 'nova-image',
    name: 'Nova Image 2',
    shortName: 'Nova 2',
    provider: 'OAOOAO Engine',
    kind: 'image',
    capability: 'image',
    description: '适合人物、产品与风格化画面',
    creditCost: 12,
    status: '可用',
    capabilities: {
      textToMedia: true,
      firstFrame: false,
      lastFrame: false,
      multiReference: true,
      editing: true,
      durations: [],
      ratios: ['1:1', '4:5', '16:9', '9:16'],
      qualities: ['标准', '高清', '超清'],
      maxReferences: 4,
      maxBatchSize: 4,
    },
  },
  {
    id: 'line-art',
    name: 'Line Art Studio',
    shortName: 'Line Art',
    provider: 'OAOOAO Engine',
    kind: 'image',
    capability: 'image',
    description: '快速探索构图与概念草图',
    creditCost: 6,
    status: '可用',
    capabilities: {
      textToMedia: true,
      firstFrame: false,
      lastFrame: false,
      multiReference: true,
      editing: true,
      durations: [],
      ratios: ['1:1', '4:5', '16:9'],
      qualities: ['标准', '高清'],
      maxReferences: 2,
      maxBatchSize: 2,
    },
  },
  {
    id: 'motion-03',
    name: 'Motion 03',
    shortName: 'Motion 03',
    provider: 'OAOOAO Engine',
    kind: 'video',
    capability: 'video',
    description: '镜头运动稳定，适合短片与广告',
    creditCost: 48,
    status: '可用',
    capabilities: {
      textToMedia: true,
      firstFrame: true,
      lastFrame: true,
      multiReference: true,
      editing: true,
      durations: ['5 秒', '8 秒', '12 秒'],
      ratios: ['16:9', '9:16', '1:1'],
      qualities: ['标准', '高清'],
      maxReferences: 3,
      maxBatchSize: 1,
    },
  },
  {
    id: 'motion-lite',
    name: 'Motion Lite',
    shortName: 'Motion Lite',
    provider: 'OAOOAO Engine',
    kind: 'video',
    capability: 'video',
    description: '轻量快速预览，不支持首尾帧',
    creditCost: 24,
    status: '演示配置',
    capabilities: {
      textToMedia: true,
      firstFrame: true,
      lastFrame: false,
      multiReference: false,
      editing: false,
      durations: ['5 秒', '8 秒'],
      ratios: ['16:9', '9:16'],
      qualities: ['标准'],
      maxReferences: 1,
      maxBatchSize: 1,
    },
  },
]

export const works: Work[] = [
  {
    id: 'work-aurora-key',
    title: '极光之后 · 主视觉',
    kind: 'image',
    src: media.auroraCover,
    fallback: '极光之后',
    projectId: 'aurora',
    status: '草稿',
    updatedAt: '刚刚',
    ratio: '16:9',
    model: 'Nova Image 2',
  },
  {
    id: 'work-city-poster',
    title: 'Northline · 夜行',
    kind: 'image',
    src: media.cityCover,
    fallback: '城市夜行',
    projectId: 'northline',
    status: '已发布',
    updatedAt: '昨天',
    ratio: '4:5',
    model: 'Nova Image 2',
  },
  {
    id: 'work-quiet-room',
    title: '安静的房间 · 03',
    kind: 'image',
    src: media.stillLife,
    fallback: '安静的房间',
    projectId: 'quiet-room',
    status: '已发布',
    updatedAt: '3 天前',
    ratio: '4:5',
    model: 'Line Art Studio',
  },
  {
    id: 'work-aurora-teaser',
    title: '极光之后 · 预告片',
    kind: 'video',
    src: media.video,
    poster: media.videoPoster,
    fallback: '极光之后预告',
    projectId: 'aurora',
    status: '处理中',
    updatedAt: '今天 08:32',
    ratio: '16:9',
    model: 'Motion 03',
  },
  {
    id: 'work-forest-path',
    title: '林间小路 · 候选 A',
    kind: 'image',
    src: media.forest,
    fallback: '林间小路',
    projectId: 'aurora',
    status: '草稿',
    updatedAt: '今天 07:10',
    ratio: '16:9',
    model: 'Motion 03',
  },
  {
    id: 'work-aurora-sky',
    title: '抬头看见极光',
    kind: 'image',
    src: media.auroraSky,
    fallback: '极光夜空',
    projectId: 'aurora',
    status: '已发布',
    updatedAt: '昨天 21:04',
    ratio: '16:9',
    model: 'Nova Image 2',
  },
  {
    id: 'work-city-night',
    title: 'Northline · 雨夜',
    kind: 'image',
    src: media.cityNight,
    fallback: '城市雨夜',
    projectId: 'northline',
    status: '已发布',
    updatedAt: '昨天 19:26',
    ratio: '16:9',
    model: 'Nova Image 2',
  },
  {
    id: 'work-interior-01',
    title: '安静的房间 · 01',
    kind: 'image',
    src: media.studio,
    fallback: '室内光线',
    projectId: 'quiet-room',
    status: '草稿',
    updatedAt: '3 天前',
    ratio: '4:5',
    model: 'Line Art Studio',
  },
  {
    id: 'work-portrait-linxia',
    title: '林夏 · 角色定妆',
    kind: 'image',
    src: media.portrait,
    fallback: '角色定妆',
    projectId: 'aurora',
    status: '已发布',
    updatedAt: '4 天前',
    ratio: '4:5',
    model: 'Nova Image 2',
  },
  {
    id: 'work-redshift-product',
    title: 'Red Shift · 产品静物',
    kind: 'image',
    src: media.product,
    fallback: '产品静物',
    projectId: 'red-shift',
    status: '已发布',
    updatedAt: '6 天前',
    ratio: '1:1',
    model: 'Nova Image 2',
  },
]

export const tasks: Task[] = [
  {
    id: 'task-aurora-01',
    type: 'video',
    title: '极光之后 · 镜头 07 预览',
    status: 'processing',
    stage: '正在生成镜头',
    createdAt: Date.parse('2026-09-14T08:57:12.000Z'),
    updatedAt: Date.parse('2026-09-14T08:57:12.000Z'),
    expectedCredits: 48,
    actualCredits: null,
    input: '女孩在雪地中回头，远处的极光开始移动，保持低饱和冷色调。',
    projectId: 'aurora',
    resultAssetIds: [],
    retryCount: 0,
    settings: { modelId: 'motion-03', ratio: '16:9', quality: '高清', duration: '8 秒' },
  },
  {
    id: 'task-northline-02',
    type: 'image',
    title: 'Northline · 城市夜行候选',
    status: 'completed',
    stage: '已完成',
    createdAt: Date.parse('2026-09-13T09:00:00.000Z'),
    updatedAt: Date.parse('2026-09-13T09:00:00.000Z'),
    expectedCredits: 12,
    actualCredits: 12,
    input: '雨后玻璃幕墙反射城市灯光，主体留出左侧排版空间。',
    projectId: 'northline',
    resultAssetIds: ['asset-city-01'],
    retryCount: 0,
    settings: { modelId: 'nova-image', ratio: '4:5', quality: '高清', count: 4 },
  },
  {
    id: 'task-quiet-room-03',
    type: 'image',
    title: '安静的房间 · 构图探索',
    status: 'failed',
    stage: '生成失败',
    createdAt: Date.parse('2026-09-12T09:00:00.000Z'),
    updatedAt: Date.parse('2026-09-12T09:00:00.000Z'),
    expectedCredits: 6,
    actualCredits: 0,
    input: '晨光落在木桌与玻璃杯上，画面安静克制。',
    projectId: 'quiet-room',
    resultAssetIds: [],
    retryCount: 1,
    error: '演示通道暂时没有可用容量，请稍后重试。',
    settings: { modelId: 'line-art', ratio: '4:5', quality: '标准', count: 2 },
  },
  {
    id: 'task-export-01',
    type: 'export',
    title: '极光之后 · 演示导出',
    status: 'queued',
    stage: '等待导出',
    createdAt: Date.parse('2026-09-14T08:59:30.000Z'),
    updatedAt: Date.parse('2026-09-14T08:59:30.000Z'),
    expectedCredits: 0,
    actualCredits: null,
    input: '基础片段编排与临时音轨',
    projectId: 'aurora',
    resultAssetIds: [],
    retryCount: 0,
    settings: { modelId: 'motion-03', ratio: '16:9', quality: '高清' },
  },
]

export const shots: StoryboardShot[] = [
  {
    id: 'shot-01',
    projectId: 'aurora',
    chapter: '第一章 · 回到这里',
    index: 1,
    title: '雪站的长椅',
    description: '林夏拖着行李走过空旷的站台，远处有一盏没有熄灭的灯。',
    dialogue: '旁白：她以为自己不会再回来。',
    duration: '06 秒',
    status: '已完成',
    referenceAssetIds: ['asset-aurora-01', 'asset-portrait-01'],
    candidates: [
      { id: 'candidate-01-a', src: media.auroraCover, title: '冷色远景', model: 'Motion 03', selected: true },
      { id: 'candidate-01-b', src: media.forest, title: '雾气近景', model: 'Motion 03', selected: false },
    ],
  },
  {
    id: 'shot-02',
    projectId: 'aurora',
    chapter: '第一章 · 回到这里',
    index: 2,
    title: '没有寄出的信',
    description: '屋内桌面上的信封被风吹开，纸张上出现一行没有写完的字。',
    dialogue: '林夏：你还记得这里吗？',
    duration: '08 秒',
    status: '需重试',
    referenceAssetIds: ['asset-portrait-01'],
    candidates: [
      { id: 'candidate-02-a', src: media.stillLife, title: '桌面静物', model: 'Motion 03', selected: false },
      { id: 'candidate-02-b', src: media.studio, title: '室内推镜', model: 'Motion Lite', selected: false },
    ],
  },
  {
    id: 'shot-03',
    projectId: 'aurora',
    chapter: '第二章 · 光线之外',
    index: 3,
    title: '林间小路',
    description: '两个人隔着一段雪地向前走，没有人先开口。',
    dialogue: '无台词',
    duration: '05 秒',
    status: '生成中',
    referenceAssetIds: ['asset-forest-01', 'asset-dancer-01'],
    candidates: [
      { id: 'candidate-03-a', src: media.forest, title: '树影移动', model: 'Motion 03', selected: true },
      { id: 'candidate-03-b', src: media.auroraSky, title: '远景留白', model: 'Motion Lite', selected: false },
    ],
  },
  {
    id: 'shot-04',
    projectId: 'aurora',
    chapter: '第二章 · 光线之外',
    index: 4,
    title: '抬头看见极光',
    description: '极光从画面外缓慢出现，两人的影子被蓝绿色的光线拉长。',
    dialogue: '旁白：有些答案，只能在天亮以前找到。',
    duration: '08 秒',
    status: '待生成',
    referenceAssetIds: ['asset-aurora-01'],
    candidates: [],
  },
]

export const orders: Order[] = [
  { id: 'order-20260912', product: 'Creator Pro 月度积分', amount: '¥128.00', credits: 2000, status: '已完成', createdAt: '2026-09-12 14:20' },
  { id: 'order-20260812', product: 'Creator Pro 月度积分', amount: '¥128.00', credits: 2000, status: '已完成', createdAt: '2026-08-12 09:15' },
  { id: 'order-20260704', product: '额外积分包 · 500', amount: '¥36.00', credits: 500, status: '退款中', createdAt: '2026-07-04 16:48' },
]

export const adminUsers: AdminUser[] = [
  { id: 'usr-1024', name: 'Mira Chen', email: 'mira@oaooao.studio', plan: 'Creator Pro', credits: 1240, tasks: 86, status: '正常', lastSeen: '刚刚' },
  { id: 'usr-1025', name: '刘一', email: 'liu.yi@example.com', plan: 'Creator', credits: 328, tasks: 24, status: '正常', lastSeen: '12 分钟前' },
  { id: 'usr-1026', name: 'Zoe Wang', email: 'zoe.w@example.com', plan: 'Free', credits: 12, tasks: 7, status: '待验证', lastSeen: '昨天' },
  { id: 'usr-1027', name: '周野', email: 'zhouye@example.com', plan: 'Creator Pro', credits: 0, tasks: 104, status: '受限', lastSeen: '3 天前' },
]

export const adminChannels: AdminChannel[] = [
  { id: 'channel-main', name: '默认生成通道', protocol: 'HTTPS / REST', mapping: 'Nova Image 2 · Motion 03', priority: 1, weight: 100, status: '演示配置', latency: '—' },
  { id: 'channel-fallback', name: '备用预览通道', protocol: 'HTTPS / REST', mapping: 'Line Art · Motion Lite', priority: 2, weight: 40, status: '已停用', latency: '—' },
]

export const adminModels: AdminModel[] = [
  { id: 'nova-image', name: 'nova-image-2', displayName: 'Nova Image 2', kind: 'image', provider: 'OAOOAO Engine', creditCost: 12, status: '展示中' },
  { id: 'motion-03', name: 'motion-03', displayName: 'Motion 03', kind: 'video', provider: 'OAOOAO Engine', creditCost: 48, status: '展示中' },
  { id: 'motion-lite', name: 'motion-lite', displayName: 'Motion Lite', kind: 'video', provider: '待接入', creditCost: 24, status: '维护中' },
]

export const defaultNav = [
  { href: '/', label: '首页' },
  { href: '/image', label: '图片' },
  { href: '/video', label: '视频' },
  { href: '/projects', label: '项目' },
  { href: '/assets', label: '素材' },
  { href: '/tasks', label: '任务' },
  { href: '/works', label: '作品' },
  { href: '/gallery', label: '广场' },
]

export const defaultAdminNav = [
  { slug: 'overview', label: '运营概览' },
  { slug: 'users', label: '用户管理' },
  { slug: 'models', label: '模型与展示名称' },
  { slug: 'channels', label: '渠道管理' },
  { slug: 'tasks', label: '任务与生成记录' },
  { slug: 'products', label: '商品和计费规则' },
  { slug: 'orders', label: '支付与订单' },
  { slug: 'marketing', label: '邀请和营销' },
  { slug: 'announcements', label: '公告' },
  { slug: 'settings', label: '存储、邮件及站点设置' },
]
